// Compatibility barrel. Keep this public surface stable for stores and views.
export {
  ChatWithSupplier,
  CheckSupplier,
  DeleteCatalogModel,
  DeleteSupplier,
  EnsurePluginProvider,
  FetchModelsFromProvider,
  GetSuppliersPage,
  isPluginVendor,
  ListModelCatalog,
  ListSupplierHealth,
  ListSuppliers,
  pluginProviderDefaults,
  SaveCatalogModel,
  SaveSupplier,
} from "./api/providers_models";
export {
  DeleteAuthKey,
  DeleteEndpoint,
  DeleteModelAlias,
  GetAuthKeySecret,
  GetAuthKeysPage,
  GetEndpointsPage,
  ListAuthKeys,
  ListEndpoints,
  ListModelAliases,
  ListRoutePolicies,
  ListRoutingRules,
  SaveAuthKey,
  SaveEndpoint,
  SaveModelAlias,
  SaveRoutePolicy,
} from "./api/routes_endpoints_keys";
export {
  ClearTrafficRequests,
  GetOverview,
  GetTrafficPage,
  GetUiPrefs,
  ReloadProxy,
  SaveUiPrefs,
  State,
} from "./api/runtime_traffic";
export {
  ListPlugins,
  ListPluginUIPages,
  DiscoverPlugins,
  InstallPlugin,
  RegisterPlugin,
  UnregisterPlugin,
  SetPluginEnabled,
  StartPlugin,
  StopPlugin,
  RestartPlugin,
  GetPluginHealth,
} from "./api/plugins";

export {
  GetProjectSettings,
  SaveProjectSettings,
  getAppVersion,
  getServerConfig,
  getServerURL,
  saveServerConfig,
  serverStatus,
  wakeServer,
} from "./api/wails_settings";
