// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppVersion():Promise<string>;

export function GetServerConfig():Promise<main.ServerConfig>;

export function GetServerProcessInfo():Promise<main.ServerProcessInfo>;

export function SaveServerConfig(arg1:main.ServerConfig):Promise<void>;

export function ServerStatus():Promise<string>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
