// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSupplier(arg1) {
  return window['go']['main']['App']['CheckSupplier'](arg1);
}

export function DeleteAuthKey(arg1) {
  return window['go']['main']['App']['DeleteAuthKey'](arg1);
}

export function DeleteEndpoint(arg1) {
  return window['go']['main']['App']['DeleteEndpoint'](arg1);
}

export function DeleteModelAlias(arg1) {
  return window['go']['main']['App']['DeleteModelAlias'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['main']['App']['DeleteSupplier'](arg1);
}

export function GetAuthKeySecret(arg1) {
  return window['go']['main']['App']['GetAuthKeySecret'](arg1);
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetProjectSettings() {
  return window['go']['main']['App']['GetProjectSettings']();
}

export function GetUiPrefs() {
  return window['go']['main']['App']['GetUiPrefs']();
}

export function ListAuthKeys() {
  return window['go']['main']['App']['ListAuthKeys']();
}

export function ListEndpoints() {
  return window['go']['main']['App']['ListEndpoints']();
}

export function ListModelAliases() {
  return window['go']['main']['App']['ListModelAliases']();
}

export function ListRoutePolicies() {
  return window['go']['main']['App']['ListRoutePolicies']();
}

export function ListSupplierHealth() {
  return window['go']['main']['App']['ListSupplierHealth']();
}

export function ListSuppliers() {
  return window['go']['main']['App']['ListSuppliers']();
}

export function ReloadProxy() {
  return window['go']['main']['App']['ReloadProxy']();
}

export function SaveAuthKey(arg1) {
  return window['go']['main']['App']['SaveAuthKey'](arg1);
}

export function SaveEndpoint(arg1) {
  return window['go']['main']['App']['SaveEndpoint'](arg1);
}

export function SaveModelAlias(arg1) {
  return window['go']['main']['App']['SaveModelAlias'](arg1);
}

export function SaveProjectSettings(arg1) {
  return window['go']['main']['App']['SaveProjectSettings'](arg1);
}

export function SaveRoutePolicy(arg1) {
  return window['go']['main']['App']['SaveRoutePolicy'](arg1);
}

export function SaveSupplier(arg1) {
  return window['go']['main']['App']['SaveSupplier'](arg1);
}

export function SaveUiPrefs(arg1) {
  return window['go']['main']['App']['SaveUiPrefs'](arg1);
}

export function State() {
  return window['go']['main']['App']['State']();
}
