// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {api} from '../models';

export function CheckSupplier(arg1:string):Promise<Array<services.HealthRecord>>;

export function DeleteAuthKey(arg1:string):Promise<Array<models.AuthKeyRecord>>;

export function DeleteEndpoint(arg1:string):Promise<Array<models.EndpointRecord>>;

export function DeleteModelAlias(arg1:string):Promise<Array<models.ModelAliasRecord>>;

export function DeleteSupplier(arg1:string):Promise<Array<models.SupplierRecord>>;

export function GetAuthKeySecret(arg1:string):Promise<string>;

export function GetOverview():Promise<Record<string, any>>;

export function GetProjectSettings():Promise<services.Values>;

export function GetUiPrefs():Promise<models.Preferences>;

export function ListAuthKeys():Promise<Array<models.AuthKeyRecord>>;

export function ListEndpoints():Promise<Array<models.EndpointRecord>>;

export function ListModelAliases():Promise<Array<models.ModelAliasRecord>>;

export function ListRoutePolicies():Promise<Array<models.RoutePolicyRecord>>;

export function ListSupplierHealth():Promise<Array<services.HealthRecord>>;

export function ListSuppliers():Promise<Array<models.SupplierRecord>>;

export function ReloadProxy():Promise<Record<string, any>>;

export function SaveAuthKey(arg1:models.AuthKeyUpsertInput):Promise<Array<models.AuthKeyRecord>>;

export function SaveEndpoint(arg1:models.EndpointUpsertInput):Promise<Array<models.EndpointRecord>>;

export function SaveModelAlias(arg1:models.ModelAliasUpsertInput):Promise<Array<models.ModelAliasRecord>>;

export function SaveProjectSettings(arg1:services.Values):Promise<services.Values>;

export function SaveRoutePolicy(arg1:models.UpsertInput):Promise<Array<models.RoutePolicyRecord>>;

export function SaveSupplier(arg1:models.SupplierUpsertInput):Promise<Array<models.SupplierRecord>>;

export function SaveUiPrefs(arg1:models.Preferences):Promise<models.Preferences>;

export function State():Promise<api.State>;
