// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {supplier} from '../models';
import {authkey} from '../models';
import {endpoint} from '../models';
import {modelalias} from '../models';
import {projectsettings} from '../models';
import {uiprefs} from '../models';
import {routepolicy} from '../models';
import {api} from '../models';

export function CheckSupplier(arg1:string):Promise<Array<supplier.HealthRecord>>;

export function DeleteAuthKey(arg1:string):Promise<Array<authkey.Record>>;

export function DeleteEndpoint(arg1:string):Promise<Array<endpoint.Record>>;

export function DeleteModelAlias(arg1:string):Promise<Array<modelalias.Record>>;

export function DeleteSupplier(arg1:string):Promise<Array<supplier.Record>>;

export function GetAuthKeySecret(arg1:string):Promise<string>;

export function GetOverview():Promise<Record<string, any>>;

export function GetProjectSettings():Promise<projectsettings.Values>;

export function GetUiPrefs():Promise<uiprefs.Preferences>;

export function ListAuthKeys():Promise<Array<authkey.Record>>;

export function ListEndpoints():Promise<Array<endpoint.Record>>;

export function ListModelAliases():Promise<Array<modelalias.Record>>;

export function ListRoutePolicies():Promise<Array<routepolicy.Record>>;

export function ListSupplierHealth():Promise<Array<supplier.HealthRecord>>;

export function ListSuppliers():Promise<Array<supplier.Record>>;

export function ReloadProxy():Promise<Record<string, any>>;

export function SaveAuthKey(arg1:authkey.UpsertInput):Promise<Array<authkey.Record>>;

export function SaveEndpoint(arg1:endpoint.UpsertInput):Promise<Array<endpoint.Record>>;

export function SaveModelAlias(arg1:modelalias.UpsertInput):Promise<Array<modelalias.Record>>;

export function SaveProjectSettings(arg1:projectsettings.Values):Promise<projectsettings.Values>;

export function SaveRoutePolicy(arg1:routepolicy.UpsertInput):Promise<Array<routepolicy.Record>>;

export function SaveSupplier(arg1:supplier.UpsertInput):Promise<Array<supplier.Record>>;

export function SaveUiPrefs(arg1:uiprefs.Preferences):Promise<uiprefs.Preferences>;

export function State():Promise<api.State>;
