// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:number):Promise<void>;

export function CloseWindow():Promise<void>;

export function DebugRoute(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteProvider(arg1:string):Promise<void>;

export function GetGatewayConfig():Promise<string>;

export function GetGatewayRequestLogs(arg1:number):Promise<string>;

export function GetGatewayStatus():Promise<string>;

export function GetModels():Promise<string>;

export function GetProviderModels(arg1:string):Promise<string>;

export function GetProviders():Promise<string>;

export function GetRouteRules():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function RefreshModels():Promise<string>;

export function SetGatewayConfig(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:number,arg7:string):Promise<void>;

export function SetProviderModels(arg1:string,arg2:Array<config.ModelEntry>,arg3:string):Promise<void>;

export function SetRouteRules(arg1:Array<config.RouteRuleConfig>):Promise<void>;

export function StartGateway():Promise<void>;

export function StopGateway():Promise<void>;

export function TestProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function UpdateProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:number):Promise<void>;
