// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['services']['App']['AddProvider'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CloseWindow() {
  return window['go']['services']['App']['CloseWindow']();
}

export function DeleteProvider(arg1) {
  return window['go']['services']['App']['DeleteProvider'](arg1);
}

export function GetGatewayConfig() {
  return window['go']['services']['App']['GetGatewayConfig']();
}

export function GetGatewayRequestLogs(arg1) {
  return window['go']['services']['App']['GetGatewayRequestLogs'](arg1);
}

export function GetGatewayStatus() {
  return window['go']['services']['App']['GetGatewayStatus']();
}

export function GetModels() {
  return window['go']['services']['App']['GetModels']();
}

export function GetProviderModels(arg1) {
  return window['go']['services']['App']['GetProviderModels'](arg1);
}

export function GetProviders() {
  return window['go']['services']['App']['GetProviders']();
}

export function GetRouteRules() {
  return window['go']['services']['App']['GetRouteRules']();
}

export function Greet(arg1) {
  return window['go']['services']['App']['Greet'](arg1);
}

export function MinimizeWindow() {
  return window['go']['services']['App']['MinimizeWindow']();
}

export function RefreshModels() {
  return window['go']['services']['App']['RefreshModels']();
}

export function SetGatewayConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['App']['SetGatewayConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetProviderModels(arg1, arg2, arg3) {
  return window['go']['services']['App']['SetProviderModels'](arg1, arg2, arg3);
}

export function SetRouteRules(arg1) {
  return window['go']['services']['App']['SetRouteRules'](arg1);
}

export function StartGateway() {
  return window['go']['services']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['services']['App']['StopGateway']();
}

export function TestProvider(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['App']['TestProvider'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateProvider(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['services']['App']['UpdateProvider'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
