// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddAPIKey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string,arg7:Array<string>,arg8:Array<string>):Promise<void>;

export function AddEndpoint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:boolean,arg10:number,arg11:boolean,arg12:string):Promise<void>;

export function AddProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:number):Promise<void>;

export function CloseWindow():Promise<void>;

export function DeleteAPIKey(arg1:string):Promise<void>;

export function DeleteEndpoint(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function GetAPIKeys():Promise<string>;

export function GetEndpoints():Promise<string>;

export function GetGatewayConfig():Promise<string>;

export function GetGatewayRequestLogs(arg1:number):Promise<string>;

export function GetGatewayStatus():Promise<string>;

export function GetModels():Promise<string>;

export function GetProviderModels(arg1:string):Promise<string>;

export function GetProviders():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function RefreshModels():Promise<string>;

export function SetGatewayConfig(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:number):Promise<void>;

export function SetProviderModels(arg1:string,arg2:Array<config.ModelEntry>,arg3:string):Promise<void>;

export function StartGateway():Promise<void>;

export function StopGateway():Promise<void>;

export function TestProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function UpdateAPIKey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string,arg7:Array<string>,arg8:Array<string>):Promise<void>;

export function UpdateEndpoint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:boolean,arg10:number,arg11:boolean,arg12:string):Promise<void>;

export function UpdateProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:number):Promise<void>;
